import React, { useEffect, useState } from 'react';
import { doc, getDoc } from 'firebase/firestore';
import { auth, db } from '../firebase/config';
import { onAuthStateChanged } from 'firebase/auth';
import ProtectedFeature from '../components/ProtectedFeature';
import { jsPDF } from "jspdf"; // ✅ 1. Library Import karein

const PdfGenerator = () => {
  const [subscription, setSubscription] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (user) => {
      if (user) {
        const docRef = doc(db, 'subscriptions', user.uid);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
          setSubscription(docSnap.data());
        }
      }
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  // ✅ 2. Asli PDF Download karne ka function
  // PdfGenerator.jsx ke andar downloadPdf function ko update karein:

  const downloadPdf = () => {
    try {
      const doc = new jsPDF();

      doc.setFontSize(20);
      doc.setTextColor(255, 0, 0);
      doc.text("SAASCORE PREMIUM REPORT", 20, 20);

      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`User Email: ${auth.currentUser?.email}`, 20, 40);

      // ✅ Yahan se default values hata di hain
      doc.text(`Subscription Plan: ${subscription?.name || "N/A"}`, 20, 50);
      doc.text(`Status: ${subscription?.status || "active"}`, 20, 60);
      doc.text(`Billing Amount: $${subscription?.amount || "0"}`, 20, 70);

      doc.text("--------------------------------------------------", 20, 80);
      doc.text("This document is generated by your SaaS platform", 20, 90);
      doc.text("for premium subscribed users only.", 20, 100);

      doc.save(`${subscription?.name || "SaaS"}_Report.pdf`);
    } catch (error) {
      console.error("PDF Error:", error);
    }
  };

  if (loading) return <div className="text-white text-center mt-20">Verifying Access...</div>;

  return (
    <ProtectedFeature subscription={subscription}>
      <div className="min-h-screen flex flex-col items-center justify-center bg-black text-white px-6">
        <h1 className="text-4xl font-black mb-6 text-yellow-400">PDF Generator</h1>
        <p className="text-gray-400 mb-8 text-center max-w-md">
          Your professional PDF report is ready for export.
        </p>

        <button
          onClick={downloadPdf} // ✅ alert ki jagah ye function
          className="px-8 py-4 bg-yellow-400 text-black font-bold rounded-2xl hover:bg-yellow-300 transition-all shadow-[0_0_20px_rgba(250,204,21,0.5)]"
        >
          Download PDF Report
        </button>
      </div>
    </ProtectedFeature>
  );
};

export default PdfGenerator;